language: objective-c 
osx_image: xcode8.2.1
xcode_workspace: IosContinuousIntegration.xcworkspace
xcode_scheme: IosContinuousIntegration
xcode_sdk: 'iPhone 7'
before_script: 
  - gem update fastlane
  - pod repo update
  - pod install
script: 
  - fastlane ios test