language: objective-c 
cache: cocoapods
osx_image: xcode8.2.1
xcode_workspace: IosContinuousIntegration.xcworkspace
xcode_scheme: IosContinuousIntegration
xcode_sdk: 'iPhone 7'
script: 
- fastlane ios test