language: objective-c 
osx_image: xcode8.2.1
xcode_workspace: IosContinuousIntegration.xcworkspace
xcode_scheme: IosContinuousIntegration
xcode_sdk: 'iPhone 6s'
before_install:
  - pod install
script: 
  - fastlane ios test