language: objective-c 
osx_image: xcode7.3.1
xcode_workspace: IosContinuousIntegration.xcworkspace
xcode_scheme: IosContinuousIntegration
xcode_sdk: 'iPhone 6s'
before_install:
  # Force bundler 1.12.5 because version 1.13 has issues, see https://github.com/fastlane/fastlane/issues/6065#issuecomment-246044617
  - gem install bundler -v 1.13.7 --no-rdoc --no-ri --no-document --quiet
  - gem cleanup
before_script: 
  - pod install
script: 
  - fastlane ios test