language: objective-c 
osx_image: xcode7.3.1
xcode_workspace: IosContinuousIntegration.xcworkspace
xcode_scheme: IosContinuousIntegration
xcode_sdk: 'iPhone 6s'
before_script: 
  - gem update fastlane
  - pod install
script: 
  - fastlane ios test